# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
---
name: Spellcheck

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "radblog/**"
      - ".github/workflows/spellcheck.yaml"
      - ".github/config/**"
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
    paths:
      - "radblog/**"
      - ".github/workflows/spellcheck.yaml"
      - ".github/config/**"

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Spellcheck
        uses: rojopolis/spellcheck-github-actions@6f2326b663e2dbab920da0fc4144b9f3202434ba # 0.54.0
        with:
          config_path: .github/config/.pyspelling.yml
