# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
---
name: Spellcheck

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - radblog/**
      - .github/workflows/spellcheck.yaml
      - .github/config/**
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
    paths:
      - radblog/**
      - .github/workflows/spellcheck.yaml
      - .github/config/**

permissions: {}

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Spellcheck
        uses: rojopolis/spellcheck-github-actions@79c6662f156bc4faa184a458c39cd672783804b3 # 0.59.0
        with:
          config_path: .github/config/.pyspelling.yml
